### ISSUE TITLE
Initialize CDK Content

### ISSUE THREAD

**Issue by DannyS03** [0xPolygon/wiki#13]
## Context

This task concentrates on initializing the CDK content for our Wiki.

Polygon Chain Development Kit (CDK) is the next-generation successor to the existing Supernets product suite. It is also a critical component of Polygon 2.0. For more details about the current Supernets product suite, please refer to our Edge client-based Supernets documentation [here](https://wiki.polygon.technology/docs/supernets).

The CDK framework employs zkValidium, a technology that expands on the implementation of Polygon's zkEVM, with the addition of a data availability layer overseen by a Data Availability Committee (DAC).

## Done Criteria

- [x] Create a temporary new entry on the Navbar for Polygon 2.0 (the design is subject to future changes).
- [x] Establish a new CDK section in the sidebars.js.
- [x] Craft a "What are CDK" overview, highlighting the essence and capabilities of zkSupernets.
    - [x] Provide a brief explanation of what CDK are and their functionality.
    - [x] Provide contextual section on app-chains, data availability, and validiums.
    - [x] Introduce a "Why CDK" section.
    - [x] Highlight the CDK program.
- [x] Produce a system attributes doc that distinctly convey the functionality.
- [x] Produce a technical overview of the DAC.
   - [x] Define data availability and the role of DACs.
   - [x] Indicate that the CDK is essentially the zkEVM tied together with an additional data availability layer (DAC).
   - [x] Include a breakdown of data flow.
   - [x] Include an overview of zkEVM and outline that CDK use the same implementation.
   - [x] Compare with zkEVM.
- [x] Generate a standalone document dedicated to the CDK program.
- [x] Produce an index page for CDK.
- [x] Produce a quickstart guide to launch a simple test (CDK-developed) network.
- [ ] Ensure associated repository READMEs are updated.

## Additional Information

The primary aim of these initial documents is to serve as an accessible starting point for a diverse range of audiences, facilitating their understanding of Polygon CDK.

We also plan to follow this with a new set of product documentation that will diverge from the existing Supernets documentation.

**Comment by DannyS03** [comment]
**2023-07-18 Update**:
 
- Initial drafts shared internally with team via staged preview.
- Addressing feedback from Product, SolEng, & BD.
- Target is to propose changes and release by Friday.

**Comment by DannyS03** [comment]
**2023-07-21 Update**:

- Drafts complete.
- Pending external contribution for first Quick Start guide.
- Pending reviews from various stakeholders.

**Comment by DannyS03** [comment]
**2023-07-26 Update**:

- Legal review complete.
- Pending confirmation of *naming*.
- Quick Start draft is ready.

**Comment by DannyS03** [comment]
**2023-07-26 Update**:

Drafts have been ready, just pending the _naming_ confirmation. The plan is to confirm naming before raising PR(s).

**Comment by DannyS03** [comment]
**2023-08-29 Update**:

Docs updated and repurposed to align with the latest product offering: the Chain Development Kit (CDK).
